package battleship;

enum PossibleFieldValues {
    SPACE(new Position(0, 0)),
    ONE  (new Position(1, 0)),
    TWO  (new Position(2, 0)),
    THREE(new Position(3, 0)),
    FOUR (new Position(4, 0)),
    FIVE (new Position(5, 0)),
    SIX  (new Position(6, 0)),
    SEVEN(new Position(7, 0)),
    EIGHT(new Position(8, 0)),
    NINE (new Position(9, 0)),
    TEN  (new Position(10, 0)),

    A    (new Position(0, 1)),
    A1   (new Position(1, 1)),
    A2   (new Position(2, 1)),
    A3   (new Position(3, 1)),
    A4   (new Position(4, 1)),
    A5   (new Position(5, 1)),
    A6   (new Position(6, 1)),
    A7   (new Position(7, 1)),
    A8   (new Position(8, 1)),
    A9   (new Position(9, 1)),
    A10  (new Position(10, 1)),

    B    (new Position(0, 2)),
    B1   (new Position(1, 2)),
    B2   (new Position(2, 2)),
    B3   (new Position(3, 2)),
    B4   (new Position(4, 2)),
    B5   (new Position(5, 2)),
    B6   (new Position(6, 2)),
    B7   (new Position(7, 2)),
    B8   (new Position(8, 2)),
    B9   (new Position(9, 2)),
    B10  (new Position(10, 2)),

    C    (new Position(0, 3)),
    C1   (new Position(1, 3)),
    C2   (new Position(2, 3)),
    C3   (new Position(3, 3)),
    C4   (new Position(4, 3)),
    C5   (new Position(5, 3)),
    C6   (new Position(6, 3)),
    C7   (new Position(7, 3)),
    C8   (new Position(8, 3)),
    C9   (new Position(9, 3)),
    C10  (new Position(10, 3)),

    D    (new Position(0, 4)),
    D1   (new Position(1, 4)),
    D2   (new Position(2, 4)),
    D3   (new Position(3, 4)),
    D4   (new Position(4, 4)),
    D5   (new Position(5, 4)),
    D6   (new Position(6, 4)),
    D7   (new Position(7, 4)),
    D8   (new Position(8, 4)),
    D9   (new Position(9, 4)),
    D10  (new Position(10, 4)),

    E    (new Position(0, 5)),
    E1   (new Position(1, 5)),
    E2   (new Position(2, 5)),
    E3   (new Position(3, 5)),
    E4   (new Position(4, 5)),
    E5   (new Position(5, 5)),
    E6   (new Position(6, 5)),
    E7   (new Position(7, 5)),
    E8   (new Position(8, 5)),
    E9   (new Position(9, 5)),
    E10  (new Position(10, 5)),

    F    (new Position(0, 6)),
    F1   (new Position(1, 6)),
    F2   (new Position(2, 6)),
    F3   (new Position(3, 6)),
    F4   (new Position(4, 6)),
    F5   (new Position(5, 6)),
    F6   (new Position(6, 6)),
    F7   (new Position(7, 6)),
    F8   (new Position(8, 6)),
    F9   (new Position(9, 6)),
    F10  (new Position(10, 6)),

    G    (new Position(0, 7)),
    G1   (new Position(1, 7)),
    G2   (new Position(2, 7)),
    G3   (new Position(3, 7)),
    G4   (new Position(4, 7)),
    G5   (new Position(5, 7)),
    G6   (new Position(6, 7)),
    G7   (new Position(7, 7)),
    G8   (new Position(8, 7)),
    G9   (new Position(9, 7)),
    G10  (new Position(10, 7)),

    H    (new Position(0, 8)),
    H1   (new Position(1, 8)),
    H2   (new Position(2, 8)),
    H3   (new Position(3, 8)),
    H4   (new Position(4, 8)),
    H5   (new Position(5, 8)),
    H6   (new Position(6, 8)),
    H7   (new Position(7, 8)),
    H8   (new Position(8, 8)),
    H9   (new Position(9, 8)),
    H10  (new Position(10, 8)),

    I    (new Position(0, 9)),
    I1   (new Position(1, 9)),
    I2   (new Position(2, 9)),
    I3   (new Position(3, 9)),
    I4   (new Position(4, 9)),
    I5   (new Position(5, 9)),
    I6   (new Position(6, 9)),
    I7   (new Position(7, 9)),
    I8   (new Position(8, 9)),
    I9   (new Position(9, 9)),
    I10  (new Position(10, 9)),

    J    (new Position(0, 10)),
    J1   (new Position(1, 10)),
    J2   (new Position(2, 10)),
    J3   (new Position(3, 10)),
    J4   (new Position(4, 10)),
    J5   (new Position(5, 10)),
    J6   (new Position(6, 10)),
    J7   (new Position(7, 10)),
    J8   (new Position(8, 10)),
    J9   (new Position(9, 10)),
    J10  (new Position(10, 10));

    private final Position position;

    PossibleFieldValues(Position position) {
        this.position = position;
    }

    public Position getPosition() {
        return position;
    }
}
